### ISSUE TITLE
杭州租房活跃小组ID共享

### ISSUE THREAD

**Issue by ZJM6658** [jiahui92/taro-douban-group-filter#3]
562889,602744,120199,582169,582792,641616,276209,276209,554566,576850,hzhouse,HZhome,467221,145219

-只是杭州的活跃小组，复制粘贴进去就可以了

**Comment by jiahui92** [comment]
> 562889,602744,120199,582169,582792,641616,276209,276209,554566,576850,hzhouse,HZhome,467221,145219
> 
> -只是杭州的活跃小组，复制粘贴进去就可以了

谢谢，已经更新进接口里了

**Comment by jiahui92** [comment]
done
